# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="arrow"
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs)

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_last"

POWERLEVEL9K_COLOR_SCHEME='light'
# POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
# POWERLEVEL9K_SHORTEN_DELIMITER=""

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# This should be enabled if tmux keeps renaming windows.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git autojump zsh-syntax-highlighting git-flow-completion)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Locales
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
export LANG LC_ALL

# Default editor
export EDITOR=vim

# Set root path to dotfiles
export DOTFILES=$HOME/Tools/dotfiles

# Autojump (Brew)
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

autoload -U compinit; compinit

# Chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby 2.6.3

# ZSH includes
source $DOTFILES/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $DOTFILES/zsh/aliases

# QT
export PATH=$PATH:$HOME/Qt/5.12.0/clang_64/bin:$HOME/Qt/Tools/QtInstallerFramework/3.0/bin

# Android
export ANDROID_AVD_HOME=~/.android/avd
export ANDROID_HOME=~/Library/Android/sdk
export ANDROID_SDK_HOME=~/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_HOME/emulator:$ANDROID_SDK_HOME/tools/bin:$ANDROID_SDK_HOME/tools

# Vortex
source $DOTFILES/zsh/vortex/android_envs

# Visual Studio Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Homebrew
export PATH=/usr/local/bin:$PATH

# ReactNative
# function rn-clean() {
#   watchman watch-del-all
#   rm -rf $TMPDIR/react-*
#   rm -rf $TMPDIR/haste-*
#   rm -rf $TMPDIR/metro-*
#   npm start -- --reset-cache
# }

# Flutter
export PATH="$PATH:/$HOME//Development/flutter/bin"
